automation:
  - id: evening_porch_on
    alias: 'Porch light on around sunset'
    trigger:
      - platform: sun
        event: sunset
        offset: "-00:30:00"
    action:
      - delay: "00:{{- ((range(1,9) | random) ~ '').rjust(2, '0') -}}:00"
      - service: switch.turn_on
        entity_id: switch.porch_light_switch

  - id: night_porch_off
    alias: 'Turn the porch light off at night'
    trigger:
      - platform: time
        at: '23:00:00'
    action:
      - service: switch.turn_off
        entity_id: switch.porch_light_switch
