homeassistant:
  customize:
    media_player.living_room_2:
      friendly_name: Living Room Music

media_player:
  - platform: roku
    host: 192.168.1.227

  - platform: cast
    host: 192.168.1.230

  - platform: onkyo
    host: 192.168.1.221
    name: Receiver
